name: Publish Jupyter Notebooks

on:
  push:
    branches: [ main, docs ]

jobs:
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
            
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Install Prerequists
        run: |
          python -m pip install --upgrade pip
          pip install sphinxcontrib-jupyter

      - name: Generate Jupyter Notebooks
        run: |
          make jupyter
      - name: Copy over
        run: |          
          mkdir out
          cp pyproject.toml out/
          cp -r .github/ out/
          cp -r estimator/ out/
          rm -rf out/estimator/__pycache__
          echo 'FROM sagemathinc/cocalc:latest' >> out/Dockerfile
          echo 'COPY --chown=sage:sage . ${HOME}' >> out/Dockerfile
          cp doc/_build/jupyter/lwe-*.ipynb out
          cp doc/_build/jupyter/prompt.ipynb out

      - name: Publish
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: jupyter-notebooks
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
